//
// Created by Michael Shea on 8/27/22.
//

#ifndef PROGRAM3_MICHAELSHEA_BATTLEMOVEFACTORY_H
#define PROGRAM3_MICHAELSHEA_BATTLEMOVEFACTORY_H


class battlemovefactory {

};


#endif //PROGRAM3_MICHAELSHEA_BATTLEMOVEFACTORY_H
